Setup profile
VanTan291/blog-team-1 pull request #21
Opened 2022-10-08 12:50 UTC by DaTinh

Trello:
https://trello.com/c/5fOOxUc2/20-setup-profile

2022-10-08 15:21 UTC, VanTan291 requested changes

2022-10-08 15:21 UTC, VanTan291 commented on config/app.php
> +        Intervention\Image\ImageServiceProvider::class,
Ni k cần dùng đâu tính.

2022-10-08 15:21 UTC, VanTan291 commented on config/app.php
> +        'Image' => Intervention\Image\Facades\Image::class,
Ni nữa

2022-10-09 15:46 UTC, DaTinh commented on config/app.php
> +        Intervention\Image\ImageServiceProvider::class,
Oke Tan

2022-10-10 14:59 UTC, merged